import React from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft2, Sms } from "iconsax-react";
import Header from "@/components/onboarding/shared/Header";

const COMPANY = "Wavetifi Limited";
const LAST_UPDATED = "April 2, 2026";
const CONTACT_EMAIL = "info@sendcoins.ca";

type Block =
  | { type: "p"; text: string }
  | { type: "bullets"; items: string[] }
  | { type: "definitions"; items: { term: string; def: string }[] };

type Section = { title: string; blocks: Block[] };

const slug = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

const SECTIONS: Section[] = [
  {
    title: "General Terms",
    blocks: [
      {
        type: "p",
        text: `By accessing and placing an order with ${COMPANY}, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and our team. Under no circumstance shall our team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if representative has been advised of the possibility of such damage. If your misuse of materials from this site results in the need for servicing, repair or loss of any kind, you assume any costs thereof. ${COMPANY}, will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy at any moment.`,
      },
    ],
  },
  {
    title: "License",
    blocks: [
      {
        type: "p",
        text: `${COMPANY} grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the service strictly in accordance with the terms of this Agreement. These Terms & Conditions are a contract between you and ${COMPANY}.`,
      },
    ],
  },
  {
    title: "Definitions and Key Terms",
    blocks: [
      { type: "p", text: "For this Terms & Conditions:" },
      {
        type: "definitions",
        items: [
          {
            term: "Cookie",
            def: "Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.",
          },
          {
            term: "Company",
            def: 'When this policy mentions "Company," "we," "us," or "our," it refers to members of our team responsible for your information under this Privacy Policy.',
          },
          {
            term: "Country",
            def: `Where the owners/founders of ${COMPANY} are based — currently Nigeria.`,
          },
          {
            term: "Customer",
            def: "Refers to the company, organization or person that signs up to use our Service.",
          },
          {
            term: "Device",
            def: "Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit the application and use the services.",
          },
          {
            term: "IP Address",
            def: "Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.",
          },
          {
            term: "Personnel",
            def: `Refers to those individuals who are employed by ${COMPANY} or are under contract to perform a service on behalf of one of the parties.`,
          },
          {
            term: "Personal Data",
            def: "Any information that directly, indirectly, or in connection with other information including a personal identification number allows for the identification or identifiability of a natural person.",
          },
          {
            term: "Service",
            def: `Refers to the service provided by ${COMPANY} as described in the relative terms and on this platform.`,
          },
          {
            term: "Third-party Service",
            def: "Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",
          },
          {
            term: "Website",
            def: `${COMPANY}'s site, accessible via our URL.`,
          },
          {
            term: "You",
            def: `A person or entity that is registered with ${COMPANY} to use the Services.`,
          },
        ],
      },
    ],
  },
  {
    title: "Restrictions",
    blocks: [
      { type: "p", text: "You agree not to, and you will not permit others to:" },
      {
        type: "bullets",
        items: [
          "License, sell, use, copy, host, outsource, disclose or otherwise commercially exploit the service or make the platform available to any third party.",
          "Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the service.",
          "Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of or its affiliates, partners, suppliers or the licensors of the service.",
        ],
      },
    ],
  },
  {
    title: "Return and Refund Policy",
    blocks: [
      {
        type: "p",
        text: "Thanks for your patronage. We appreciate the fact that you have employed the use of our services/platform. We also want to make sure you have a rewarding experience while you're exploring, evaluating, and purchasing our products and services. As with any patronage/usage experience, there are terms and conditions that apply to transactions at our company. The main thing to remember is that by placing an order or making a purchase from us, you agree to the terms along with our Privacy Policy. If, for any reason, you are not completely satisfied with the services we provide, don't hesitate to contact us and we will discuss any of the issues you have encountered in the course of using our product.",
      },
    ],
  },
  {
    title: "Your Suggestions",
    blocks: [
      {
        type: "p",
        text: `Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to us with respect to the service shall remain the sole and exclusive property of ${COMPANY}. We shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.`,
      },
    ],
  },
  {
    title: "Your Consent",
    blocks: [
      {
        type: "p",
        text: "We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our service, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.",
      },
    ],
  },
  {
    title: "Links to Other Websites",
    blocks: [
      {
        type: "p",
        text: "Our service may contain links to other websites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Terms & Conditions of every site you visit. We have no control over and assume no responsibility for the content, Terms & Conditions or practices of any third party sites or services.",
      },
    ],
  },
  {
    title: "Cookies",
    blocks: [
      {
        type: "p",
        text: 'We use "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our service but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit our platform as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.',
      },
    ],
  },
  {
    title: "Changes to Our Terms & Conditions",
    blocks: [
      {
        type: "p",
        text: "You acknowledge and agree that we may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at our sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform us when you stop using the Service. You acknowledge and agree that if we disable access to your account you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account. If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.",
      },
    ],
  },
  {
    title: "Modifications to Our Service",
    blocks: [
      {
        type: "p",
        text: "We reserve the right to modify, suspend or discontinue, temporarily or permanently, the service or any service to which it connects, with or without notice and without liability to you.",
      },
    ],
  },
  {
    title: "Updates to Our Service",
    blocks: [
      {
        type: "p",
        text: 'We may from time to time provide enhancements or improvements to the features/functionality of the service, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates"). Updates may modify or delete certain features and/or functionalities of the service. You agree that we have no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the service to you. You further agree that all Updates will be (i) deemed to constitute an integral part of the service, and (ii) subject to the terms and conditions of this Agreement.',
      },
    ],
  },
  {
    title: "Third-Party Services",
    blocks: [
      {
        type: "p",
        text: 'We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third-Party Services"). You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services. Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties\' terms and conditions.',
      },
    ],
  },
  {
    title: "Term and Termination",
    blocks: [
      {
        type: "p",
        text: "This Agreement shall remain in effect until terminated by you or us. We may, in sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice. This Agreement will be terminated immediately, without prior notice from us, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the service and all copies thereof from your computer. Upon termination of this Agreement, you shall cease all use of the service and delete all copies of the service from your computer. Termination of this Agreement will not limit any of our rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.",
      },
    ],
  },
  {
    title: "Copyright Infringement Notice",
    blocks: [
      {
        type: "p",
        text: "If you are a copyright owner or such owner's agent and believe any material from us constitutes an infringement on your copyright, please contact us setting forth the following information: (a) a physical or electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the material that is claimed to be infringing; (c) your contact information, including your address, telephone number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and (e) a statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.",
      },
    ],
  },
  {
    title: "Indemnification",
    blocks: [
      {
        type: "p",
        text: "You agree to indemnify and hold us and our parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the service; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.",
      },
    ],
  },
  {
    title: "Limitation of Liability",
    blocks: [
      {
        type: "p",
        text: "Notwithstanding any damages that you might incur, the entire liability of us and any of our suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the service. To the maximum extent permitted by applicable law, in no event shall we or our suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the service, third-party software and/or third-party hardware used with the service, or otherwise in connection with any provision of this Agreement), if we or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose. Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.",
      },
    ],
  },
  {
    title: "Severability",
    blocks: [
      {
        type: "p",
        text: "If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect. This Agreement, together with the Privacy Policy and any other legal notices published by us on the Services, shall constitute the entire agreement between you and us concerning the Services. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and our failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. YOU AND US AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.",
      },
    ],
  },
  {
    title: "Waiver",
    blocks: [
      {
        type: "p",
        text: "Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not affect a party's ability to exercise such right or require such performance at any time thereafter nor shall the waiver of a breach constitute waiver of any subsequent breach. No failure to exercise, and no delay in exercising, on the part of either party, any right or any power under this Agreement shall operate as a waiver of that right or power. Nor shall any single or partial exercise of any right or power under this Agreement preclude further exercise of that or any other right granted herein. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern.",
      },
    ],
  },
  {
    title: "Amendments to This Agreement",
    blocks: [
      {
        type: "p",
        text: "We reserve the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use our service.",
      },
    ],
  },
  {
    title: "Entire Agreement",
    blocks: [
      {
        type: "p",
        text: `The Agreement constitutes the entire agreement between you and ${COMPANY} regarding your use of the service and supersedes all prior and contemporaneous written or oral agreements between you and us. You may be subject to additional terms and conditions that apply when you use or purchase other services from us, which we will provide to you at the time of such use or purchase.`,
      },
    ],
  },
  {
    title: "Updates to Our Terms",
    blocks: [
      {
        type: "p",
        text: "We may change our Service and policies, and we may need to make changes to these Terms so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to these Terms and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Terms. If you do not want to agree to these or any updated Terms, you can delete your account.",
      },
    ],
  },
  {
    title: "Intellectual Property",
    blocks: [
      {
        type: "p",
        text: "Our platform and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by us, its licensors or other providers of such material and are protected by international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. The material may not be copied, modified, reproduced, downloaded or distributed in any way, in whole or in part, without the express prior written permission of us, unless and except as is expressly provided in these Terms & Conditions. Any unauthorized use of the material is prohibited.",
      },
    ],
  },
  {
    title: "Agreement to Arbitrate",
    blocks: [
      {
        type: "p",
        text: `This section applies to any dispute except it doesn't include a dispute relating to claims for injunctive or equitable relief regarding the enforcement or validity of your or ${COMPANY}'s intellectual property rights. The term "dispute" means any dispute, action, or other controversy between you and us concerning the Services or this agreement, whether in contract, warranty, tort, statute, regulation, ordinance, or any other legal or equitable basis. "Dispute" will be given the broadest possible meaning allowable under law.`,
      },
    ],
  },
  {
    title: "Notice of Dispute",
    blocks: [
      {
        type: "p",
        text: `In the event of a dispute, you or us must give the other a Notice of Dispute, which is a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief requested. You must send any Notice of Dispute via email to ${CONTACT_EMAIL}. We will send any Notice of Dispute to you by mail to your address if we have it, or otherwise to your email address. You and us will attempt to resolve any dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty (60) days, you or us may commence arbitration.`,
      },
    ],
  },
  {
    title: "Binding Arbitration",
    blocks: [
      {
        type: "p",
        text: "If you and us don't resolve any dispute by informal negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration as described in this section. You are giving up the right to litigate (or participate in as a party or class member) all disputes in court before a judge or jury. The dispute shall be settled by binding arbitration in accordance with the commercial arbitration rules of the Nigerian Arbitration Association. Either party may seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party's rights or property pending the completion of arbitration. Any and all legal, accounting, and other costs, fees, and expenses incurred by the prevailing party shall be borne by the non-prevailing party.",
      },
    ],
  },
  {
    title: "Submissions and Privacy",
    blocks: [
      {
        type: "p",
        text: "In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data or proposals, including ideas for new or improved products, services, features, technologies or promotions, you expressly agree that such submissions will automatically be treated as non-confidential and non-proprietary and will become the sole property of us without any compensation or credit to you whatsoever. We and our affiliates shall have no obligations with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services using such ideas.",
      },
    ],
  },
  {
    title: "Promotions",
    blocks: [
      {
        type: "p",
        text: 'We may, from time to time, include contests, promotions, sweepstakes, or other activities ("Promotions") that require you to submit material or information concerning yourself. Please note that all Promotions may be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age and geographic location. You are responsible to read all Promotions rules to determine whether or not you are eligible to participate. If you enter any Promotion, you agree to abide by and to comply with all Promotion\'s Rules. Additional terms and conditions may apply to purchases of goods or services on or through the Services.',
      },
    ],
  },
  {
    title: "Typographical Errors",
    blocks: [
      {
        type: "p",
        text: "In the event a product and/or service is listed at an incorrect price or with incorrect information due to typographical error, we shall have the right to refuse or cancel any orders placed for the product and/or service listed at the incorrect price. We shall have the right to refuse or cancel any order whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is canceled, we shall immediately issue a credit to your credit card account or other payment account in the amount of the charge.",
      },
    ],
  },
  {
    title: "Miscellaneous",
    blocks: [
      {
        type: "p",
        text: "If for any reason a court of competent jurisdiction finds any provision or portion of these Terms & Conditions to be unenforceable, the remainder of these Terms & Conditions will continue in full force and effect. Any waiver of any provision of these Terms & Conditions will be effective only if in writing and signed by an authorized representative of our team. We will be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you. We operate and control our Service from our offices in Nigeria. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. These Terms & Conditions (which include and incorporate our Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and us concerning its subject matter, and cannot be changed or modified by you.",
      },
    ],
  },
  {
    title: "Disclaimer",
    blocks: [
      {
        type: "p",
        text: 'We are not responsible for any content, code or any other imprecision. We do not provide warranties or guarantees. In no event shall we be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. We reserve the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice. Our Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether expressed or implied. We are a distributor and not a publisher of the content supplied by third parties; as such, we exercise no editorial control over such content and make no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via our Service. Without limiting the foregoing, we specifically disclaim all warranties and representations in any content transmitted on or in connection with our Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by us or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, we do not warrant that our Service will be uninterrupted, uncorrupted, timely, or error-free.',
      },
    ],
  },
  {
    title: "Data Retention",
    blocks: [
      {
        type: "p",
        text: `We retain your personal data only for as long as is necessary to provide you with the ${COMPANY} service and for legitimate, essential business purposes — such as maintaining the performance of the service, making data-driven business decisions, complying with our legal obligations, and resolving disputes.`,
      },
      {
        type: "bullets",
        items: [
          "Account & profile data — retained for the duration of your active account and for up to 90 Days after account deletion or last activity, unless a longer retention period is required by law.",
          "Health & pregnancy tracking data — retained while your account is active. Upon account deletion, this data is permanently removed within 90 days.",
          "Communication records (e.g. support emails) — retained for up to 2 years from the date of last communication.",
        ],
      },
      {
        type: "p",
        text: "When your data is no longer required, we securely delete or anonymise it so that it can no longer be associated with you.",
      },
    ],
  },
  {
    title: "Data Deletion & Your Right to Erasure",
    blocks: [
      {
        type: "p",
        text: "You have the right to request the deletion of your personal data at any time. You can do this in the following ways:",
      },
      {
        type: "bullets",
        items: [
          `In-app deletion — Go to Settings → Account → Delete Account in the ${COMPANY} app. This will immediately begin the deletion process for your account and associated personal data.`,
          `Email request — Send a deletion request to ${CONTACT_EMAIL} with the subject line "Data Deletion Request" and include the email address linked to your account.`,
        ],
      },
      {
        type: "p",
        text: "Once we receive your verified request, we will permanently delete your personal data within 30 days, except where we are required to retain certain data to comply with a legal obligation (for example, financial transaction records), resolve a dispute, or enforce our agreements.",
      },
      {
        type: "p",
        text: `We will send you a confirmation email once your data has been fully deleted. If you have any questions about this process, please contact us at ${CONTACT_EMAIL}.`,
      },
    ],
  },
];

const Block: React.FC<{ block: Block }> = ({ block }) => {
  if (block.type === "p") {
    return <p className="text-[15px] leading-7 text-neutral-600">{block.text}</p>;
  }
  if (block.type === "bullets") {
    return (
      <ul className="mt-1 space-y-2">
        {block.items.map((item, i) => (
          <li key={i} className="flex gap-3 text-[15px] leading-7 text-neutral-600">
            <span className="mt-[10px] h-1.5 w-1.5 shrink-0 rounded-full bg-[#0647F7]" />
            <span>{item}</span>
          </li>
        ))}
      </ul>
    );
  }
  return (
    <dl className="mt-1 space-y-4">
      {block.items.map((d, i) => (
        <div
          key={i}
          className="rounded-xl border border-neutral-100 bg-neutral-50/60 px-4 py-3"
        >
          <dt className="text-sm font-semibold text-neutral-900">{d.term}</dt>
          <dd className="mt-1 text-[15px] leading-7 text-neutral-600">{d.def}</dd>
        </div>
      ))}
    </dl>
  );
};

const Terms: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-white">
      <Header />

      {/* Top bar */}
      <div className="mx-auto max-w-5xl px-4 md:px-8">
        <button
          onClick={() => navigate("/login")}
          className="inline-flex items-center gap-2 rounded-full border border-neutral-200 px-4 py-2 text-sm font-semibold text-neutral-700 transition hover:bg-neutral-50"
        >
          <ArrowLeft2 size="16" color="currentColor" />
          Back to Home
        </button>
      </div>

      {/* Hero */}
      <div className="mx-auto max-w-5xl px-4 pt-8 pb-6 text-center md:px-8">
        <span className="inline-flex items-center rounded-full bg-[#EEF2FF] px-3 py-1 text-xs font-semibold uppercase tracking-wide text-[#0647F7]">
          Legal
        </span>
        <h1 className="mt-4 text-[34px] font-semibold leading-tight text-neutral-900 md:text-[42px]">
          Terms &amp; Conditions
        </h1>
        <p className="mx-auto mt-3 max-w-2xl text-[15px] leading-7 text-neutral-500">
          Please read these terms carefully before using our service. By
          accessing or using {COMPANY}, you agree to be bound by these terms.
        </p>
        <p className="mt-4 text-sm text-neutral-400">Last updated: {LAST_UPDATED}</p>
      </div>

      {/* Content + sticky TOC */}
      <div className="mx-auto max-w-5xl px-4 pb-20 md:px-8">
        <div className="lg:grid lg:grid-cols-[230px_1fr] lg:gap-12">
          {/* TOC */}
          <aside className="hidden lg:block">
            <nav className="sticky top-8 max-h-[calc(100vh-4rem)] overflow-y-auto pr-2">
              <p className="mb-3 text-xs font-semibold uppercase tracking-wide text-neutral-400">
                On this page
              </p>
              <ul className="space-y-1.5">
                {SECTIONS.map((s) => (
                  <li key={s.title}>
                    <a
                      href={`#${slug(s.title)}`}
                      className="block rounded-md px-2 py-1 text-[13px] leading-5 text-neutral-500 transition hover:bg-neutral-50 hover:text-[#0647F7]"
                    >
                      {s.title}
                    </a>
                  </li>
                ))}
              </ul>
            </nav>
          </aside>

          {/* Body */}
          <main className="min-w-0">
            <div className="rounded-2xl border border-neutral-100 bg-white p-6 shadow-[0_1px_3px_rgba(0,0,0,0.04)] md:p-10">
              {SECTIONS.map((section, idx) => (
                <section
                  key={section.title}
                  id={slug(section.title)}
                  className={`scroll-mt-8 ${idx > 0 ? "mt-10 border-t border-neutral-100 pt-10" : ""}`}
                >
                  <h2 className="text-xl font-semibold text-neutral-900">
                    {section.title}
                  </h2>
                  <div className="mt-3 space-y-4">
                    {section.blocks.map((block, i) => (
                      <Block key={i} block={block} />
                    ))}
                  </div>
                </section>
              ))}

              {/* Contact card */}
              <section
                id="contact-us"
                className="mt-10 scroll-mt-8 border-t border-neutral-100 pt-10"
              >
                <h2 className="text-xl font-semibold text-neutral-900">Contact Us</h2>
                <p className="mt-3 text-[15px] leading-7 text-neutral-600">
                  If you have any questions about these Terms &amp; Conditions,
                  please contact us:
                </p>
                <div className="mt-4 grid gap-3 sm:grid-cols-2">
                  <a
                    href={`mailto:${CONTACT_EMAIL}`}
                    className="flex items-center gap-3 rounded-xl border border-neutral-100 bg-neutral-50/60 px-4 py-3 transition hover:border-[#0647F7]/30"
                  >
                    <span className="grid h-10 w-10 place-items-center rounded-full bg-[#EEF2FF]">
                      <Sms size="20" color="#0647F7" variant="Bold" />
                    </span>
                    <span>
                      <span className="block text-xs text-neutral-400">Email</span>
                      <span className="text-sm font-medium text-neutral-900">
                        {CONTACT_EMAIL}
                      </span>
                    </span>
                  </a>
                  <button
                    onClick={() => navigate("/contact")}
                    className="flex items-center gap-3 rounded-xl border border-neutral-100 bg-neutral-50/60 px-4 py-3 text-left transition hover:border-[#0647F7]/30"
                  >
                    <span className="grid h-10 w-10 place-items-center rounded-full bg-[#EEF2FF]">
                      <ArrowLeft2 size="20" color="#0647F7" className="rotate-180" />
                    </span>
                    <span>
                      <span className="block text-xs text-neutral-400">Send a message</span>
                      <span className="text-sm font-medium text-neutral-900">
                        Contact form
                      </span>
                    </span>
                  </button>
                </div>
              </section>
            </div>

            {/* Footer */}
            <div className="mt-8 flex flex-col items-center gap-4 text-center">
              <p className="text-sm text-neutral-400">
                © {new Date().getFullYear()} {COMPANY}. All rights reserved.
              </p>
              <button
                onClick={() => navigate("/login")}
                className="inline-flex items-center gap-2 text-sm font-semibold text-[#0647F7] transition hover:underline"
              >
                <ArrowLeft2 size="16" color="currentColor" />
                Back to Home
              </button>
            </div>
          </main>
        </div>
      </div>
    </div>
  );
};

export default Terms;
